CREATE TABLE `session` (
	`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`status` CHAR(6) NOT NULL DEFAULT 'OPEN',
	`type` CHAR(3) NOT NULL DEFAULT 'CMD',
	`reason` TEXT NOT NULL DEFAULT '',
	`time_opened` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`time_closed` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	`log_file` VARCHAR(256) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`)
) ENGINE=InnoDB;
